### ISSUE TITLE
macOS build is missing version

### ISSUE THREAD

**Issue by raphaelreyna** [raphaelreyna/oneshot#14]
I'm not entirely sure whats causing this but I think its an issue with [goreleaser](https://github.com/goreleaser/goreleaser)

**Comment by jedi2610** [comment]
Check issue #15 
The problem arises because the URL to the download file is not correct and throws a error while trying to download.
I had to manually change the URL and download it.

**Comment by raphaelreyna** [comment]
> Check issue #15
> The problem arises because the URL to the download file is not correct and throws a error while trying to download.
> I had to manually change the URL and download it.

I really doubt this is related to issue #15 since I still get a blank version number after doing a manual install and not using the provided installation script. Also, the version is set during compilation using the -ldflags option and the installation script never handles compilation.
