### ISSUE TITLE
Cannot connect to the IP address

### ISSUE THREAD

**Issue by jedi2610** [raphaelreyna/oneshot#17]
I am running Windows 7 and I can't seem to connect to that machine from other devices. Is it some bug in the program or do I need to manually change some network visibility options?

**Comment by raphaelreyna** [comment]
If both devices are on the same local network and can ping each other, I'm not sure what the issue could be here. To my knowledge, this isn't happening on any of the other major platforms. Windows 7 is no longer supported by Microsoft so I won't be looking into this. However I will leave this open and would be happy to look at any PRs that solve this.

**Comment by jedi2610** [comment]
i had to manually set the specific port open for all connections in windows firewall. that was the issue
