### ISSUE TITLE
bind localhost only

### ISSUE THREAD

**Issue by patatetom** [raphaelreyna/oneshot#21]
hi,
oneshot is a cool tool ;-)
we can change the listening port : would it also be possible to change the address ? to bind only localhost for example (e.g. behind apache or nginx).
regards, lacsaP.

**Comment by raphaelreyna** [comment]
> oneshot is a cool tool ;-)

Thanks!


This is a feature that should have been present since the very beginning, thanks for pointing it out!
I should have this implemented soon.
