### ISSUE TITLE
zip file structure is broken

### ISSUE THREAD

**Issue by jedi2610** [raphaelreyna/oneshot#23]
**Describe the bug**
while sending folders as zip files the structure of zip files is broken
say for example i'm sending a folder `Downloads/folder` then the zip file structure while extracting is `folder/folder/*.*`

**To Reproduce**
`oneshot -a zip path to any folder`

**Expected behavior**
the file structure while extracting should be like `folder/*.*` instead of `folder/folder/*.*`

**Desktop:**
 - OS: arch linux
 - Version: 1.3.1

**Comment by raphaelreyna** [comment]
Thanks for letting me know! I'll be looking into it soon.

**Comment by raphaelreyna** [comment]
I can't seem to reproduce this error. I tried sending the `internal` folder of this repo as a zip archive: `oneshot -a zip ./internal`.

Here's what I get when I unzip the archive:
```
$ unzip ~/Downloads/internal.zip
Archive:  /home/rr/Downloads/internal.zip
  inflating: internal/file/reader.go  
  inflating: internal/file/tar.go    
  inflating: internal/file/writer.go  
  inflating: internal/file/zip.go    
  inflating: internal/handlers/authenticate.go  
  inflating: internal/handlers/bots.go  
  inflating: internal/handlers/cgi.go  
  inflating: internal/handlers/download.go  
  inflating: internal/handlers/redirect.go  
  inflating: internal/handlers/upload.go  
  inflating: internal/server/add-route.go  
  inflating: internal/server/route.go  
  inflating: internal/server/server.go  
```

If I'm understanding this correctly, unzip is inflating to `internal/internal/file/reader.go`... etc. for you?

**Comment by jedi2610** [comment]
@raphaelreyna yeah that's correct. maybe I'll try it again later and let you know?

**Comment by jedi2610** [comment]
@raphaelreyna it's works fine if i extract the file on my pc. i generally use this program to send files b/w my pc and my phone. while extracting the zip files on my phone this problem occurs. strange idk what's wrong with my file manager. i'll close this issue now as it's not related to the program.
