### ISSUE TITLE
Invalid CSRF token

### ISSUE THREAD

**Issue by nasserbinlaboun** [raphaelreyna/oneshot#24]
**Describe the bug**
When trying to upload a file, it shows this error:
`error :: 2021/08/05 17:17:03 server.go:128: Invalid CSRF token`

**To Reproduce**
1. Run `oneshot -u .`
2. Upload file from a browser.
3. It shows this error `error :: 2021/08/05 17:17:03 server.go:128: Invalid CSRF token`

**Expected behavior**
File Uploaded Successfully.

**Output and error messages**
`error :: 2021/08/05 17:17:03 server.go:128: Invalid CSRF token`

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version v1.5.0

**Comment by raphaelreyna** [comment]
Thanks for the bug report!
This is now fixed in [v1.5.1](https://github.com/raphaelreyna/oneshot/releases/tag/v1.5.1)
