### ISSUE TITLE
Send command uses public IP address instead of private.

### ISSUE THREAD

**Issue by lukasnxyz** [raphaelreyna/oneshot#38]
**Describe the bug**
I don't know if this is in purpose, but I've been using oneshot for a while now and it's always used my computers private IP address (LAN). I downloaded oneshot-bin via paru today and ran it trying to transfer a pdf file and it opened the server on my LAN's public_ip:8080 instead of my machine's private_ip:8080.

**To Reproduce**
oneshot send "path/to/file.pdf"

**Expected behavior**
listening on http://private_ip:8080

**Output and error messages**
listening on http://public_ip:8080

**Desktop**
 - OS: Arch Linux
 - Kernel Version: 6.6.10-arch1-1

**Comment by raphaelreyna** [comment]
thanks for reporting this.
yeah that shouldn't be happening.
are you using v2.0.1? (`oneshot version`)

if so, i'm pretty sure the external ip should only be used when upnp nat traversal is being used.
do you mind posting the output of `oneshot config get nattraversal.upnp`?

also, you can get debug logs by setting environment variables `ONESHOT_LOG_LEVEL=debug` and `ONESHOT_LOG_STDERR=true`, that could help debug this.

**Comment by lukasnxyz** [comment]
Hi, 
I reinstalled my os a couple of days ago (for other reasons), just tried this again and it works fine, so unfortunately I can't reproduce the error. 
I think it may have had something to-do with my LAN because I live in a student dormitory with a very weird WiFi network including username/password and many separate sub-LAN's. Maybe something with the network had messed up then.

Cheers!
